import "/styles/globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { Baskervville, Montserrat } from "next/font/google";

import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

import NavBar from "@/_components/NavBar";
import Footer from '@/_components/Footer'


const fontSerif = Baskervville({subsets: [ "latin"], weight: ["400"], variable: '--font-serif'});

const fontSans = Montserrat({subsets: [ "latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  params: { locale: string };
};

export default async function RootLayout({
  children,
  params: { locale },
}: Props) {
  const messages = await getMessages();
  return (
    <html lang={locale} className="h-full">
      <body className={`${fontSans.className} ${fontSerif.variable} h-full`}>
        <NextIntlClientProvider messages={messages}>
          <NavBar />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
